name: Rust

on: [push, pull_request]


jobs:
  build_test_spec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly
          - beta
          - stable
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Obtain Rust
      run: rustup override set ${{ matrix.rust }}
    - name: Build and test
      run: env SPEC=false script/cibuild
    - name: Run spec tests
      run: env SPEC=true script/cibuild
  no_features_build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly
          - beta
          - stable
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Obtain Rust
      run: rustup override set ${{ matrix.rust }}
    - name: Build and test with no features
      run: cargo test --no-default-features --tests
  lockfile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Obtain Rust
      run: rustup override set stable
    - name: Build and test with no features
      run: cargo +stable build --locked --release --all-features
  clippy_format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Obtain Rust
      run: rustup override set ${{ matrix.rust }}
    - name: Check clippy
      run: rustup component add clippy && cargo clippy
    - name: Check formatting
      run: rustup component add rustfmt && cargo fmt -- --check
